In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("globalAirQuality.csv")
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [3]:
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [4]:
df.tail()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [5]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [6]:
#selecting data
#column wise
df["country"]
df[["city", "aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [7]:
#row wise
df.loc[0]

timestamp      2025-11-04 18:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               50.295
pm10                              108.938
no2                                27.998
so2                                 6.539
o3                                 52.568
co                                  1.096
aqi                                   108
temperature                        18.504
humidity                           70.168
wind_speed                          3.725
Name: 0, dtype: object

In [8]:
df.loc[0:2]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [9]:
df.iloc[2]

timestamp      2025-11-04 20:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                                42.25
pm10                               82.553
no2                                26.935
so2                                 9.538
o3                                  23.32
co                                  0.977
aqi                                    84
temperature                        31.833
humidity                           62.783
wind_speed                           9.65
Name: 2, dtype: object

In [10]:
df.iloc[0:2]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [11]:
df.loc[0, ["city", "aqi"]]

city    New York
aqi          108
Name: 0, dtype: object

In [12]:
df.loc[0:3, ["city", "aqi"]]

       city  aqi
0  New York  108
1  New York   90
2  New York   84
3  New York  158

In [13]:
df.columns

Index(['timestamp', 'country', 'city', 'latitude', 'longitude', 'pm25', 'pm10',
       'no2', 'so2', 'o3', 'co', 'aqi', 'temperature', 'humidity',
       'wind_speed'],
      dtype='object')

In [14]:
df.iloc[0:4, [2,11]]

       city  aqi
0  New York  108
1  New York   90
2  New York   84
3  New York  158

In [15]:
df.iloc[0:4, [1,2,3,4]]

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006
3      US  New York    40.713    -74.006

In [16]:
df.at[0, "city"]

'New York'

In [17]:
cities = df["city"].copy()
cities[0] = "Mumbai"
cities.head()

0      Mumbai
1    New York
2    New York
3    New York
4    New York
Name: city, dtype: object

In [18]:
df["city"].head()

0    New York
1    New York
2    New York
3    New York
4    New York
Name: city, dtype: object

In [19]:
#Filtering
df[df["aqi"] > 200]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
745,2025-11-05 19:25:17.554219,GB,London,51.507,-0.128,107.144,43.819,13.389,4.601,21.680,0.890,214,19.055,66.245,1.637
8941,2025-11-17 07:25:17.554219,JP,Osaka,34.694,135.502,102.142,95.204,41.688,7.806,28.951,0.753,204,15.277,76.131,4.586
12956,2025-11-19 14:25:17.554219,NZ,Auckland,-36.848,174.763,44.824,66.657,90.019,3.637,41.311,0.849,225,14.872,63.319,0.958
14555,2025-11-11 05:25:17.554219,PH,Manila,14.600,120.984,103.023,66.678,43.284,2.167,48.250,0.849,206,11.027,63.522,7.635
17458,2025-11-12 04:25:17.554219,FI,Helsinki,60.170,24.938,14.329,51.173,81.111,7.725,61.160,1.383,202,34.420,26.061,3.771
17529,2025-11-15 03:25:17.554219,FI,Helsinki,60.170,24.938,115.683,81.714,54.764,6.687,39.552,0.685,231,25.795,87.839,6.705
17815,2025-11-12 01:25:17.554219,CH,Zurich,47.377,8.542,54.805,39.178,81.406,10.241,46.579,0.498,203,20.883,70.201,3.500

In [20]:
df[(df["aqi"] > 190) & (df["temperature"] > 30)]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
112,2025-11-09 10:25:17.554219,US,New York,40.713,-74.006,96.012,102.666,38.339,6.486,42.027,1.643,192,32.786,32.631,6.679
3115,2025-11-14 13:25:17.554219,MX,Mexico City,19.433,-99.133,98.327,97.741,23.343,8.865,46.702,0.713,196,30.738,66.421,1.256
6747,2025-11-15 21:25:17.554219,IN,Mumbai,19.076,72.878,62.908,19.589,77.649,7.903,65.652,0.919,194,32.153,53.831,1.480
6783,2025-11-17 09:25:17.554219,IN,Mumbai,19.076,72.878,95.929,61.409,48.361,7.268,37.606,1.331,191,37.271,83.946,6.947
7024,2025-11-12 10:25:17.554219,IN,Delhi,28.704,77.102,44.382,45.774,78.190,4.611,5.395,0.991,195,34.274,49.015,3.470
8841,2025-11-13 03:25:17.554219,JP,Osaka,34.694,135.502,62.694,81.679,76.758,0.279,52.622,1.191,191,35.043,77.867,9.509
11564,2025-11-06 14:25:17.554219,ID,Jakarta,-6.209,106.846,40.484,79.717,79.303,7.311,30.245,0.702,198,36.710,78.685,4.315
11891,2025-11-05 05:25:17.554219,AU,Sydney,-33.869,151.209,96.517,88.197,32.500,6.503,63.414,0.638,193,34.785,53.453,8.300
12776,2025-11-12 02:25:17.554219,NZ,Auckland,-36.848,174.763,58.672,99.358,78.586,4.415,67.490,1.449,196,34.282,55.299,9.528
17458,2025-11-12 04:25:17.554219,FI,Helsinki,60.170,24.938,14.329,51.173,81.111,7.725,61.160,1.383,202,34.420,26.061,3.771

In [21]:
aqi_data = df[df["aqi"] > 200][["city", "aqi"]]
aqi_data

           city  aqi
745      London  214
8941      Osaka  204
12956  Auckland  225
14555    Manila  206
17458  Helsinki  202
17529  Helsinki  231
17815    Zurich  203

In [22]:
aqi_data.loc[745]

city    London
aqi        214
Name: 745, dtype: object

In [23]:
aqi_data.iloc[0]

city    London
aqi        214
Name: 745, dtype: object

In [24]:
#Filtering with query method
df.query("aqi > 190 & temperature > 30")[["city", "aqi"]]

              city  aqi
112       New York  192
3115   Mexico City  196
6747        Mumbai  194
6783        Mumbai  191
7024         Delhi  195
8841         Osaka  191
11564      Jakarta  198
11891       Sydney  193
12776     Auckland  196
17458     Helsinki  202

In [25]:
aqi_value = 190
df.query("aqi > @aqi_value & temperature > 30")[["city", "aqi"]]

              city  aqi
112       New York  192
3115   Mexico City  196
6747        Mumbai  194
6783        Mumbai  191
7024         Delhi  195
8841         Osaka  191
11564      Jakarta  198
11891       Sydney  193
12776     Auckland  196
17458     Helsinki  202