In [1]:
import pandas as pd

In [4]:
#DataFrame

info = {
    "Name": ["Ishwari", "Pranita", "Saee", "Vaishnavi"],
    "Roll_No": [44, 10, 48, 58]
}
df = pd.DataFrame(info)
df

        Name  Roll_No
0    Ishwari       44
1    Pranita       10
2       Saee       48
3  Vaishnavi       58

In [6]:
#Series with index
s = pd.Series([23, 24, 18, 19])
print(s)
print(s[0])
print(s[3])

0    23
1    24
2    18
3    19
dtype: int64
23
19

In [8]:
#Series with label

s = pd.Series([23, 24, 18, 19], index = ["Ishwari", "Vaishnavi", "Saee", "Pranita"])
print(s)
print(s["Ishwari"])
print(s[1])

Ishwari      23
Vaishnavi    24
Saee         18
Pranita      19
dtype: int64
23
24

C:\Users\Acer\AppData\Local\Temp\ipykernel_16752\2581093368.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[1])

In [11]:
#DataFrame

#using dictionary
info = {
    "Name": ["A", "B", "C"],
    "Age": [19, 20, 21]
}
df = pd.DataFrame(info)
df

  Name  Age
0    A   19
1    B   20
2    C   21

In [13]:
#using list of lists
infol = [["A", 23], ["B", 20], ["C", 21]]
df = pd.DataFrame(infol, columns = ["Name", "Age"])
df

  Name  Age
0    A   23
1    B   20
2    C   21

In [14]:
#using numpy array
import numpy as np
arr = np.array([["A", 26], ["B", 30], ["C", 21]])
df = pd.DataFrame(arr, columns = ["Name", "Age"])
df

  Name Age
0    A  26
1    B  30
2    C  21

In [15]:
df = pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [21]:
df.head()

   id          name   age country   gender   income
0   1      John Doe  29.0     USA     Male  55000.0
1   1      John Doe  29.0     USA     Male  55000.0
2   2    Jane Smith   NaN  Canada   Female  62000.0
3   3          Alex   NaN     USA  Unknown  47000.0
4   4  Maria Garcia  34.0   Spain   Female      NaN

In [22]:
df.tail(2)

    id         name   age country gender   income
9    9  Carlos Ruiz   NaN  Mexico   Male  45000.0
10  10  Emily Davis  31.0     USA    NaN  58000.0

In [23]:
df.sample()

   id      name   age country gender   income
1   1  John Doe  29.0     USA   Male  55000.0

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       11 non-null     int64
 1   name     10 non-null     object
 2   age      8 non-null      float64
 3   country  10 non-null     object
 4   gender   10 non-null     object
 5   income   10 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 660.0+ bytes

In [26]:
df.shape

(11, 6)

In [27]:
df.describe()

              id        age        income
count  11.000000   8.000000     10.000000
mean    5.090909  32.750000  57600.000000
std     3.176619   6.065123   8896.940798
min     1.000000  27.000000  45000.000000
25%     2.500000  29.000000  52000.000000
50%     5.000000  30.000000  56500.000000
75%     7.500000  35.000000  62000.000000
max    10.000000  45.000000  73000.000000

In [30]:
df.columns

Index(['id', 'name', 'age', 'country', 'gender', 'income'], dtype='object')

In [31]:
df.nunique()

id         10
name        9
age         6
country     6
gender      3
income      8
dtype: int64